name: Build Wheel with uv build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Build wheel with uv build
        run: uv venv .venv && source .venv/bin/activate && uv pip install . && uv build --wheel -o dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
